apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: social-backend:latest
          imagePullPolicy: Never
          command: ["node", "infra/workers/worker.js"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
