apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
labels:
  - pairs:
      env: stress-no-hpa

patches:
  - target:
      version: v1
      kind: Service
      name: backend
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

