version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: social_z_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - social_z_network

volumes:
  redis_data:

networks:
  social_z_network:
    driver: bridge